"""empty message

Revision ID: 8209201adcd7
Revises: 23280244009f
Create Date: 2020-03-30 16:57:48.961302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8209201adcd7'
down_revision = '23280244009f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_fighters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fighter_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'fighter_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_fighters')
    # ### end Alembic commands ###
