version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            python -m pytest -v ./tests

workflows:
  Workflow:
    jobs:
      - tests