version: 2.1
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            pip install -r requirements.txt

  test-unit:
    steps:
      - run:
          name: run tests
          command: |
            python -m pytest -v ./tests/unit
            
  test-functional:
    steps:
      - run:
          name: run tests
          command: |
            python -m pytest -v ./tests/functional

workflows:
  Workflow:
    jobs:
      - test-unit
      - test-functional:
          requires:
            - test-unit
